Add option to have the search widget under item panel
GTNewHorizons/NotEnoughItems pull request #364
Opened 2023-03-29 02:05 UTC by Caedis

Closes #317

New option (default true)
![image](https://user-images.githubusercontent.com/18713839/228407344-7967245f-27dd-4684-9e55-f66ec34d0509.png)

Center Search + Quantity Widget:
![image](https://user-images.githubusercontent.com/18713839/228407107-becf75b9-e1cf-4c8e-abae-51d059fb3cd0.png)

Center Search off + Quantity Widget:
![image](https://user-images.githubusercontent.com/18713839/228407158-92eb3e43-58bc-4105-8891-3aa44bae146c.png)

Center Search off + Quantity Widget off:
![image](https://user-images.githubusercontent.com/18713839/228407206-5c6c427e-1d9a-49a0-9b35-4794feb32515.png)

Thoughts on increasing the size of the quantity widget to match the search widget?

2023-03-29 07:05 UTC, Caedis commented
Also not sure if the other locale files need updating or if they default to the English locale if its not found.

2023-04-01 10:50 UTC, wlhlm requested changes
Nice change overall 👍 Tested and working nicely.

Yes, the translation will default to English, so everything's fine on that front.

I like the vertical arrangement of the +/- buttons. However I'd expect those buttons to be on the right of the input field having used similar widgets in other applications/toolkits. My main example would be the HTML5 number input field. Maybe this something I'm used to from left-to-right locales/languages.

Either way, I think the +/- need to be closer to the stack size input field instead of the search field. Currently it looks like they belong to the search field.
![2023-04-01_12 18 58](https://user-images.githubusercontent.com/1928113/229284411-06f7d26a-1093-4817-98f3-fa590e3b1094.png)

2023-04-01 11:13 UTC, Dream-Master commented
@Caedis

2023-04-01 17:02 UTC, OneEyeMaker submitted a review, later dismissed

2023-04-01 17:02 UTC, OneEyeMaker commented on src/main/java/codechicken/nei/ItemPanel.java
> +            less.x = (int) (x + (w * 0.7));
Should this coefficient be constant (0.7) or depend on `NEIClientConfig.showItemQuantityWidget()`?

2023-04-01 19:40 UTC, Caedis commented
Gotcha, how does this look?
![image](https://user-images.githubusercontent.com/18713839/229310893-782d7952-3204-4507-8f7e-c51fbb5b5517.png)

Still thinking if I want to increase the size of the search bar

2023-04-01 19:50 UTC, wlhlm commented
> Gotcha, how does this look?

Exactly what I had in mind. 👍 

> Still thinking if I want to increase the height of the search bar

I agree. Maybe the same height as the centered search bar (and increase the stack size bar to be the same height)? Or parity with JEI? I hardly ever played with JEI, so I don't really remember how its layout is exactly...

2023-04-01 19:51 UTC, Caedis commented
JEI does not have the quantity widget

2023-04-01 19:51 UTC, wlhlm commented
I was thinking about the search bar height specifically.

2023-04-01 19:55 UTC, Caedis commented
Oh, yeah

![image](https://user-images.githubusercontent.com/18713839/229311485-2173fec7-d9d7-4436-8946-c6a15242d821.png)

2023-04-01 19:59 UTC, Caedis commented
and with no quantity widget (and less columns)
![image](https://user-images.githubusercontent.com/18713839/229311623-720979da-9bfd-4371-9e72-0eb6769b0e56.png)

2023-04-01 19:59 UTC, Caedis commented
Lemme see how it looks in GTNH then i'll commit

2023-04-01 20:13 UTC, wlhlm commented
I think we should increase the quantity widget in the default layout as well to match the search bar layout. What do you think? Makes it more consistent.

2023-04-01 20:29 UTC, Caedis commented
![image](https://user-images.githubusercontent.com/18713839/229312655-10534830-fc6a-4530-91a1-4acacd3b0589.png)

2023-04-01 20:39 UTC, wlhlm commented
Nice! Waiting for your push.

2023-04-01 21:09 UTC, wlhlm approved these changes

2023-04-01 21:16 UTC, merged