Update ru_RU.lang
GTNewHorizons/NotEnoughItems pull request #512
Opened 2024-08-06 19:26 UTC by cutiegin

2024-08-07 13:55 UTC, chochem commented
shouldnt this be in Paratranz?

2024-08-07 17:40 UTC, OneEyeMaker requested changes
Я отметил основные недочёты. Пожалуйста, проверь и исправь (где возможно). Учитывай единственное/множественное число (есть несоответствия, я не все нашёл).

P. S. Если желаешь продолжить переводить моды для GTNH - обратись на проект ParaTranz (https://github.com/GTNewHorizons/GTNH-Translations/blob/master/readmes/README_ru_RU.md)

2024-08-07 17:40 UTC, OneEyeMaker commented on src/main/resources/assets/nei/lang/ru_RU.lang
> +nei.options.inventory.guirecipe.shiftOverlayRecipe=Требовать удержание Shift для перемещения предметов при наложении рецепта
```suggestion
nei.options.inventory.guirecipe.shiftOverlayRecipe=Требовать удержание Shift для перемещения предметов при отображении рецепта
```

2024-08-07 17:40 UTC, OneEyeMaker commented on src/main/resources/assets/nei/lang/ru_RU.lang
> +nei.options.inventory.guirecipe.profile.false=Ложь
```suggestion
nei.options.inventory.guirecipe.profile=Профилировать рецепты
nei.options.inventory.guirecipe.profile.true=Да
nei.options.inventory.guirecipe.profile.false=Нет
```

2024-08-07 17:40 UTC, OneEyeMaker commented on src/main/resources/assets/nei/lang/ru_RU.lang
> +nei.options.inventory.disableMouseScrollTransfer.false=Ложь
Поправь здесь и в других местах. 
```suggestion
nei.options.inventory.disableMouseScrollTransfer.true=Да
nei.options.inventory.disableMouseScrollTransfer.false=Нет
```

2024-08-07 17:40 UTC, OneEyeMaker commented on src/main/resources/assets/nei/lang/ru_RU.lang
> +nei.options.inventory.collapsibleItems.enabled=Сворачиваемые предметы
```suggestion
nei.options.inventory.collapsibleItems=Группирование предметов
nei.options.inventory.collapsibleItems.enabled=Группирование предметов
```

2024-08-07 17:40 UTC, OneEyeMaker commented on src/main/resources/assets/nei/lang/ru_RU.lang
> +nei.options.inventory.itemzoom.neiOnly.tip=Увеличивать предметы только из наложений списка ингредиентов и закладок JEI.
```suggestion
nei.options.inventory.itemzoom.neiOnly=Только подсветка NEI
nei.options.inventory.itemzoom.neiOnly.true=Включено
nei.options.inventory.itemzoom.neiOnly.false=Отключено
nei.options.inventory.itemzoom.neiOnly.tip=Увеличивать предметы только из списка ингредиентов и закладок JEI.
```

2024-08-07 17:40 UTC, OneEyeMaker commented on src/main/resources/assets/nei/lang/ru_RU.lang
> +nei.options.tools.dump.itempanel.dumped=Содержимое панели предметов выгружено в %s
Изначальный вариант был более удачным. Здесь и далее стоит использовать "сохранить" вместо "выгрузить" (это же NEI, а не самосвал, чтоб выгружать)

2024-08-07 17:40 UTC, OneEyeMaker commented on src/main/resources/assets/nei/lang/ru_RU.lang
> +nei.recipe.overlay.bookmarkAmount=Сохранить с количеством
```suggestion
nei.recipe.overlay.bookmarkAmount=Сохранить с учётом количества
```

2024-08-07 17:40 UTC, OneEyeMaker commented on src/main/resources/assets/nei/lang/ru_RU.lang
> +nei.subsets.Items.Potions.Splash=Брызги
Оригинал был лучше, ведь речь идёт о *взрывных* зельях.

2024-08-08 03:32 UTC, OneEyeMaker approved these changes

2024-08-08 04:50 UTC, merged